### ISSUE TITLE
webpack-dev-server not watching changes in my imports

### ISSUE THREAD

**Issue by newtonianb** [jtangelder/sass-loader#130] opened 2015-07-26 23:01 UTC
I just setup webpack-dev-server below are some of my configs

**assets/entry.js**
```
require('./styles/style')
```

**assets/styles/style.scss**
```
@imports ('utilities/other_style.scss')
```

*  Changes to style.scss get detected and rebuilds
*  Changes to imported file other_style do not get detected

Is this supposed to work? What's the solution for this with webpack-dev-server and hot module replacement setup?

As a work around what I could do is have all my imports be required from my entry.js file (that works) the issue is what about my global SCSS variables and mixins, I would have to import them in each file, wouldn't that slow things down alot? What is the right way to go about this?

**Comment by newtonianb** [comment] 2015-07-27 02:49
Ok now I'm completely stuck

I tried to switch all my imports to require them directly with webpack but now I'm hitting the second bug
https://github.com/jtangelder/sass-loader/issues/100

So I can't use imports as they don't trigger webpack hot loader and I can't use require or node-sass craps out.

How are people dealing with this right now??

**Comment by jhnns** [comment] 2015-07-27 09:12
Does webpack recompile anything if you change a file? It could be that just HMR is not working.

I don't know about a watcher bug... what is your OS? Are any Symlinks involved (like via `npm link` or `bower link`?

**Comment by jhnns** [comment] 2015-07-27 09:12
Is that a duplicate of #102?

**Comment by newtonianb** [comment] 2015-07-27 12:24
From my entry point I require my main styles.scss
If I my make changes to scss the dev server detects these and recompile but if make changes to any of these imports it does not.

It isn't exactly the same issue as the other one as here even the first level import doesn't work.

**Comment by f0def** [comment] 2015-07-30 05:37
I met with the same problem, as described by the @newtonianb.

**Comment by janicduplessis** [comment] 2015-07-31 22:28
I have the same issue. It seems to happen only on windows because on my mac it works fine.

**Comment by newtonianb** [comment] 2015-08-01 03:16
Thanks alot!

**Comment by jhnns** [comment] 2015-08-05 15:58
Could you guys check out the current master branch and check if it works for you? I've heavily refactored the import mechanism and need more tests.

**Comment by newtonianb** [comment] 2015-08-05 23:06
@jhnns just ran a quick test up to 3 level import, all looks good (win 8.1, npm 2.10.1) ! thanks alot

**Comment by newtonianb** [comment] 2015-08-05 23:22
Actually there is something a bit dodgy although I can't confirm whether it's a new issue or from before but from

```
images/
--- my_file.png

styles/
--- my_style.scss
--- folder_a/
------ my_other_style.scss
```

**styles/my_style.scss**
```
@import 'folder_a/my_other_style'
```

**styles/folder_a/my_other_style**
```
// this works
background-image: url('../images/my_file.png');
// this doesn't work
background-image: url('../../images/my_file.png');
// this doesn't work
background-image: url('./../../images/my_file.png');
```

It seems my path is relative to the place it's being imported from? Is that normal?

**Comment by jhnns** [comment] 2015-08-06 12:39
I have added a chapter to the README about `url()`:
https://github.com/jtangelder/sass-loader#problems-with-url

It's way more complicated than in LESS which provides a mechanism that rewrites the urls...

**Closed by jhnns** 2015-08-06 12:39 UTC
