### ISSUE TITLE
scss files @import(ed) from sass fails with error "File to import not found or unreadable"

### ISSUE THREAD

**Issue by istarkov** [jtangelder/sass-loader#78] opened 2015-04-05 12:30 UTC
This works with node-sass(3.0.0-beta.4) but not work with sass-loader

for example two files

app.sass
```
@import 'notsass'
```

notsass.scss
```
.xxx{
  color: red
}
```

---

running `node-sass -i ./web/tmp/app.sass` gives us expected result
```
.xxx {
  color: red; }
```

but sass-loader gives 
```
@import 'notsass'
       ^
      File to import not found or unreadable: ./_notsass.sass
```

**Comment by jhnns** [comment] 2015-04-05 16:46
Is `notsass` a css file?

**Comment by istarkov** [comment] 2015-04-05 21:06
I've gave extension above source, `notsass.scss`

I've rewrite locally sass-loader source to support scss includes and all works fine (it's really easy to implement after underscore check), 
except in 50% run i got this issue https://github.com/webpack/webpack/issues/904#issuecomment-89773866
(I got this issue on naked sass-loader without my changes)

So i downgrade sass-loader to 0.4.2 version

**Comment by jhnns** [comment] 2015-04-10 12:28
So is this a duplicate of #73?

**Comment by istarkov** [comment] 2015-04-10 15:07
Yes. 
With small addition - Can't import a .sass module from an .scss module **and .scss module from .sass**.

**Comment by jhnns** [comment] 2015-04-10 16:18
Yep, that problem is vice versa, because the feature doesn't exist :grin:

**Closed by jhnns** 2015-04-10 16:18 UTC
