### ISSUE TITLE
Inline variables #{$i} error

### ISSUE THREAD

**Issue by juanrbachiller** [jtangelder/sass-loader#379] opened 2017-02-15 12:15 UTC
Hi!

I have an error using inline variables like:

```
@for $i from 0 through 5 {
	.foo-#{$i} {
		padding-left: 16px * $i;
	}
}
```

> CssSyntaxError: app/styles.scss:41:11: Unknown word
> You tried to parse SCSS with the standard CSS parser; try again with the postcss-scss parser
> 
>   39 | 
>   40 | 		@for $i from 0 through 5 {
> > 41 | 			.foo-#{$i} {
>      | 			       ^
>   42 | 				padding-left: 16px * $i;
>   43 | 			}

In webpack.config.js:

```
{
  test: /\.scss$/,
  exclude: /node_modules/,
  use: ExtractTextPlugin.extract([
    {
      loader: 'css-loader',
      options: {
        modules: true,
        localIdentName: '[local]--[hash:base64:6]'
      }
    },
    {
      loader: 'sass-loader'
    }
  ])
}
```

I've tried postcss-loader and some other things, but no clue yet. Any help will be very very appreciated. Thanks!

**Comment by jhnns** [comment] 2017-02-15 13:00
The error looks like the sass-loader is not active on that file. Please check that. If you still think, this is a sass-loader issue, please provide a minimal example that reproduces the error. Try to remove as much as possible.

**Comment by juanrbachiller** [comment] 2017-02-15 14:38
Thanks a lot for your answer. You're right, it is not a sass-loader issue. The problem in the runtime compilation process. I got to find the appropriate hook for it...

**Comment by jhnns** [comment] 2017-02-15 15:15
I'll close it for now. When you're sure, it's a sass-loader problem, I'll re-open it.

**Closed by jhnns** 2017-02-15 15:15 UTC

**Comment by Rinat93** [comment] 2017-11-17 13:52
Hello!
I have the same problem..
