### ISSUE TITLE
Sourcemap broken when @importing inside a css selector

### ISSUE THREAD

**Issue by wayofspark** [jtangelder/sass-loader#342] opened 2017-01-05 13:35 UTC
Sourcemaps are broken when importing inside a css selector.
This worked fine before migrating from gulp to webpack (with same node-sass version), so i assume this is an issue in the loader and not in lib-sass.

The bug is easy to reproduce : 

`
// main.scss

@import "fileA";

.my-app {
    @import "fileB";
}
`

When inspecting (any browser), styles from "fileA" will be correctly sourcemapped to "fileA.scss", but styles from fileB will point to main.scss, at the line ".my-app {"

Using : 

"webpack": "1.14.0",
"node-sass": "4.1.1",
"sass-loader": "4.1.1",
"css-loader": "0.26.1",
"style-loader": "0.13.1",

Scss loader declaration : 

{
        test    : /\.scss$/,
        loaders : ["style", "css?sourceMap&-url", "sass?sourceMap"],
        include : path.join(__dirname, 'src')
}

Same behavior if using ExtractTextPlugin instead of style loader.

**Comment by burtyish** [comment] 2017-01-19 14:36
This looks like a duplicate of #272

**Comment by jhnns** [comment] 2017-02-13 18:35
Yes, it's a duplicate.

**Closed by jhnns** 2017-02-13 18:35 UTC
