### ISSUE TITLE
Error on SASS Partials in 1.x

### ISSUE THREAD

**Issue by JamesHenry** [jtangelder/sass-loader#68] opened 2015-03-23 19:14 UTC
Hi @jhnns,

I am not a node-sass expert by any means, and so I cannot comment on exactly what the desired end result should be, but I make extensive use of SASS partials in my code and the handling of them seems to have changed when moving from 0.x to 1.x.

For example:
If I have file `_my-partial.scss`, I would expect to (as working in 0.x) be able to reference it in my main SCSS file as `@import "my-partial"`.

In 1.x, you have to explicitly write the underscore, but as I understand it, the underscore is what signifies to SASS that it is indeed a partial.

More info: http://sass-lang.com/guide

Many thanks for your hard work on sass-loader!

James

**Comment by confiks** [comment] 2015-03-24 10:29
I ran into the same issue today when upgrading to 1.0.0. All my import statements of partials yielded 'file to import not found' errors. If it is intentional that partials should now be referenced with an underscore, a note should be added to the readme.

Related question: Now issue #39 has been implemented, what is really the difference between a partial import and a regular file import?

**Comment by jhnns** [comment] 2015-03-24 12:56
The files are now resolved by webpack, and webpack doesn't care about the `_` mechanism. However, since Sass users are expecting this feature to work (although it has nothing to with the language itself and should imho not be part of the specification, but that's another topic :wink:), I'm willing to implement this feature.

If you don't want to replace all your import statements, I recommend to stick with sass-loader `0.x` for now. There are also some issues on OSX afaik #65.

**Comment by jhnns** [comment] 2015-03-31 19:19
Should be fixed with `1.0.1`

**Closed by jhnns** 2015-03-31 19:19 UTC

**Comment by mrsum** [comment] 2015-04-30 11:21
@import 'blocks/*'; -> File to import not found or unreadable: ./blocks/_*.sass

I have:
"node-sass": "^3.0.0-beta.7",
"sass-loader": "^1.0.1",

**Comment by jhnns** [comment] 2015-05-06 08:44
Is that a wildcard or do you have a file called `*.scss`? Wildcards are not supported.

**Comment by hiroshi** [comment] 2015-09-07 02:14
@mrsum FYI
for glob import, https://github.com/Aintaer/import-glob-loader seems to work for me.

**Comment by jhnns** [comment] 2015-10-23 18:24
#151 

Are globs supported by Rubysass? Why are people expecting this to work?

**Comment by atilkan** [comment] 2018-02-13 11:12
webpack causing more problem than it solves. Why this would not work i don't get it.

**Comment by evilebottnawi** [comment] 2018-02-13 11:18
@atilkan what you problem? please create issue (better with minimum reproducible test repo)
