### ISSUE TITLE
can not found file under includePaths with out underline prefix in file name 

### ISSUE THREAD

**Issue by oopschen** [jtangelder/sass-loader#110] opened 2015-06-24 00:28 UTC
please refer detail in [stackoverflow](http://stackoverflow.com/questions/31004689/webpacks-sass-loader-do-not-find-foundation-scss-file-without-underline-prefix)

Is this a bug or the feature? Please help me out, thx!

**Comment by sogko** [comment] 2015-06-24 07:13
Hi, I believe this is a duplicate of #98 

Seems like a bug (but with an ugly workaround)

**Comment by oopschen** [comment] 2015-06-28 00:53
After 10 hours's digging, i find the solution:
### libsass importer feature
**importer** in node-sass is an experimental feature, so i do some test on it. I conclude that:
When libsass encounter import directive, it first call the importer to resolve the file. 
* If any error happens, the importer must return Error or call done with an Error.
* If the importer return absolute path, the libsass read the file content. 
* If the importer return an relative path, the libsass will search in the *includePaths* if configured

### sass-loader bug
resolve process:
* resolve module in webpack by the original name
* resolve module in webpack by the name prefiexed by underline
* done or return with file: *the name prefiexed by underline*

the last step cause the bug, *it must return the original name*. Thus, the libsass will complete the job in includePath.

BTW, how can i commit the bugfix?

**Comment by sogko** [comment] 2015-06-28 00:56
hi @oopschen, 

that sounds plausible as a fix; you can try to post the suggested solution at #98 to gain more attention or simply create a pull request.

**Comment by jhnns** [comment] 2015-06-30 10:13
@oopschen Thx for investigating this! See PR for discussion.

**Comment by jhnns** [comment] 2015-07-22 23:59
Should be fixed with 1.0.3

**Closed by jhnns** 2015-07-22 23:59 UTC
