### ISSUE TITLE
compile fail with @import

### ISSUE THREAD

**Issue by otarim** [jtangelder/sass-loader#119] opened 2015-07-14 06:39 UTC
i create a repository to show this problem happen [https://github.com/otarim/troubleshoot](https://github.com/otarim/troubleshoot), it seems that sass-loader case this issue

1). run webpack --progress command and it compile fails, the stdout stay at 

![http://segmentfault.com/img/bVmHkV](http://segmentfault.com/img/bVmHkV)

2). use another entry file `works.js` and it passed

![http://segmentfault.com/img/bVmHkX](http://segmentfault.com/img/bVmHkX)

3). i change `sass-loader` to `less-loader` and use less syntax，it works too

my node version is  v0.12.2 working on mac os 10.10.1，thanks for your help：-）

**Comment by jorrit** [comment] 2015-07-14 08:40
It seems that this setup creates too many async operations, exhausting the internal libuv threads. For example, the following works:

`UV_THREADPOOL_SIZE=10 npm start`

No idea how this can be fixed in `sass-loader`.

**Comment by otarim** [comment] 2015-07-14 09:11
@jorrit tks bro~your solution works for me 😄

**Comment by jorrit** [comment] 2015-07-14 09:17
Seems the same as sass/node-sass#857.

**Comment by jorrit** [comment] 2015-07-14 09:25
Maybe sass-loader can limit the number of outstanding sass render calls to `UV_THREADPOOL_SIZE` - 1 via the `async` module or something (no idea if that makes sense).
At least let's write down this `UV_THREADPOOL_SIZE` workaround somewhere in the README.

**Comment by otarim** [comment] 2015-07-14 09:36
@jorrit agree~i spend all day working on this issue,until i replace less-loader with sass and it works, Otherwise I would have thought it's my wrong way usage,hope the author write down this workaround into README that someone else will not make the same mistake

**Comment by hoosin** [comment] 2015-07-15 03:06
@otarim tks I'll never make the same mistake again.

**Comment by hoosin** [comment] 2015-07-15 03:06
@otarim tks，I'll never make the same mistake again.

**Comment by jorrit** [comment] 2015-07-17 14:48
This is also a duplicate of #100, by the way. Let's close this issue.

Closes #119

**Comment by jhnns** [comment] 2015-08-06 14:27
Fixed with 2.0.0

**Closed by jhnns** 2015-08-06 14:27 UTC
